name: Delete Failed Workflows

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  delete-failed-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete failed workflows
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          # 设置分页参数
          per_page=100
          page=1
          
          while true; do
            # 获取工作流运行，包括分页
            workflow_runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$OWNER/$REPO/actions/runs?status=failure&per_page=$per_page&page=$page")
            
            # 提取失败的工作流运行 ID
            failed_run_ids=$(echo "$workflow_runs" | jq -r '.workflow_runs[].id')
            
            # 如果没有更多的失败运行，退出循环
            if [ -z "$failed_run_ids" ]; then
              break
            fi
            
            # 删除每个失败的工作流运行
            for run_id in $failed_run_ids; do
              echo "Deleting workflow run $run_id"
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$run_id"
            done
            
            # 增加页数以获取下一页结果
            page=$((page + 1))
          done
          
          echo "All failed workflow runs have been deleted."
