name: Delete All Releases

on:
  workflow_dispatch: # 手动触发

jobs:
  delete-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List and delete all releases (with pagination)
        run: |
          # 初始化页码和release ID列表
          page=1
          releases=""

          # 获取所有分页中的release ID
          while true; do
            echo "Fetching page $page..."
            response=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100&page=$page")

            # 检查 API 调用是否成功
            if [ "$(echo "$response" | jq -r '.[0]')" == "null" ]; then
              break
            fi

            # 追加当前页面的 release ID
            result=$(echo "$response" | jq -r '.[].id')
            releases="$releases $result"
            page=$((page + 1))
          done

          # 检查是否有 releases
          if [ -z "$releases" ]; then
            echo "No releases found."
            exit 0
          fi

          # 删除每个 release
          for id in $releases; do
            if [ -n "$id" ]; then
              echo "Deleting release ID: $id"
              curl -s -X DELETE -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$id"
            fi
          done

          echo "All releases deleted."
