name: Rename_and_Push_File

on:
  workflow_dispatch:  # 手动触发
  schedule:           # 定时触发
    - cron: '*/20 * * * *'  # 每 20 分钟执行一次

jobs:
  rename-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Copy and rename the file (overwrite if exists)
      run: cp -f adblock_reject_quantumult.list adblock_reject_quantumult.txt

    - name: Commit the new file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add adblock_reject_quantumult.txt
        git commit -m "Add or update adblock_reject_quantumult.txt" || echo "No changes to commit"

    - name: Force push changes
      run: |
        git push origin main --force
