name: Rename and Push

# 允许手动触发
on:
  workflow_dispatch:

jobs:
  rename-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Copy and rename the file
      run: cp adblock_reject_quantumult.list adblock_reject_quantumult.txt

    - name: Commit the new file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add adblock_reject_quantumult.txt
        git commit -m "Add adblock_reject_quantumult.txt"

    - name: Force push changes
      run: |
        git push origin main --force
